### ISSUE TITLE
Lazy-Load Not Working?

### ISSUE THREAD

**Issue by mdridley** [allenhwkim/angularjs-google-maps#168]
I was trying to fix an issue on my Angular page by using the new-ish lazy loading of the APIs. I ran into issues with my code, so I changed the page just to use the div tag/map example. However when I do that, I am still getting this error:

```

ReferenceError: google is not defined
    at link (http://localhost:8080/bower_components/ngmap/build/scripts/ng-map.min.js:1:10831)
    at Z (http://localhost:8080/bower_components/angular/angular.min.js:70:356)
    at J (http://localhost:8080/bower_components/angular/angular.min.js:59:484)
    at g (http://localhost:8080/bower_components/angular/angular.min.js:52:9)
    at g (http://localhost:8080/bower_components/angular/angular.min.js:52:26)
    at g (http://localhost:8080/bower_components/angular/angular.min.js:52:26)
    at http://localhost:8080/bower_components/angular/angular.min.js:51:118
    at compile (http://localhost:8080/bower_components/angular-ui-router/release/angular-ui-router.min.js:7:17755)
    at Z (http://localhost:8080/bower_components/angular/angular.min.js:70:356)
    at J (http://localhost:8080/bower_components/angular/angular.min.js:59:484) <map center="41,-87" zoom="3">

```

**Comment by allenhwkim** [comment]
Thanks for using this module. please take a look at this example, 
view-source:http://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/map-lazy-load.html

It may help you. if not, please build a plnkr, so that I can see errors on your page.

**Comment by mdridley** [comment]
Thanks. Actually that really helped. I cannot tell you what the actual issue was... I felt like I rewrote what was already there for myself, but it is working now. Thanks!

**Comment by ozgen** [comment]
view-source:http://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/map-lazy-load.html 
is not there sir, How can I find it?
Thanks for help...

**Comment by allenhwkim** [comment]
Try map-lazy-load-params.html

**Comment by ozgen** [comment]
ok thanks for help...
