### ISSUE TITLE
assets:precompile on production enviorment fails

### ISSUE THREAD

**Issue by mikes01** [allenhwkim/angularjs-google-maps#183]
Hi, I have a problem with using angularjs-google-maps in production enviorment. In development everything is ok, but I can't compile assets on production server.

Command:
>RAILS_ENV=production rake --trace assets:precompile

Results:
```
** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Execute assets:precompile
I, [2015-04-25T17:57:56.079875 #16681]  INFO -- : Writing /home/mikes/rails/EcoDriver/public/assets/app-94252b272926e36fbae605d3d25133aa.js
I, [2015-04-25T17:58:28.502049 #16681]  INFO -- : Writing /home/mikes/rails/EcoDriver/public/assets/application-8fbf87fa5189cd52f0ea4f4a696ea739.js
I, [2015-04-25T17:58:28.897157 #16681]  INFO -- : Writing /home/mikes/rails/EcoDriver/public/assets/controllers/login_ctrl-d03e64c2c537a8fedd74d00cd8f4f6ff.js
I, [2015-04-25T17:58:28.905913 #16681]  INFO -- : Writing /home/mikes/rails/EcoDriver/public/assets/controllers/loginmodalinstance-8eb12faf836219219357c3abf2fed41f.js
I, [2015-04-25T17:58:28.913854 #16681]  INFO -- : Writing /home/mikes/rails/EcoDriver/public/assets/controllers/mainpage_ctrl-8c49ca945cddea3c869c6851bfb4d399.js
I, [2015-04-25T17:58:28.921329 #16681]  INFO -- : Writing /home/mikes/rails/EcoDriver/public/assets/controllers/navbar_ctrl-ef36cc74dbba667d5f39d2c3e6d8e146.js
I, [2015-04-25T17:58:28.931117 #16681]  INFO -- : Writing /home/mikes/rails/EcoDriver/public/assets/controllers/ranikng_ctrl-1a527c570e1209a2e99dc304701b4946.js
I, [2015-04-25T17:58:28.939972 #16681]  INFO -- : Writing /home/mikes/rails/EcoDriver/public/assets/controllers/trips_ctrl-f979593576fb3c3cebaaa8e6a844730d.js
I, [2015-04-25T17:58:28.946519 #16681]  INFO -- : Writing /home/mikes/rails/EcoDriver/public/assets/routes-528f733517a0a0490706a08c0344e9db.js
I, [2015-04-25T17:58:28.957540 #16681]  INFO -- : Writing /home/mikes/rails/EcoDriver/public/assets/services/trip-5f57c1cefa483c3a5e0caf44d59caf9a.js
I, [2015-04-25T17:58:28.963135 #16681]  INFO -- : Writing /home/mikes/rails/EcoDriver/public/assets/users-18594645a42e53a5242d1f464935c3d7.js
I, [2015-04-25T17:58:46.408155 #16681]  INFO -- : Writing /home/mikes/rails/EcoDriver/public/assets/application-3d2a2d36862b13dabb63aa1e16b2cb78.css
I, [2015-04-25T17:58:46.420625 #16681]  INFO -- : Writing /home/mikes/rails/EcoDriver/public/assets/modules/_headers-545910712798558def0961f9e9ee23c1.css
I, [2015-04-25T17:58:46.429595 #16681]  INFO -- : Writing /home/mikes/rails/EcoDriver/public/assets/modules/_ranking-6458bb36166ae950b1cfc2401b4fdb7f.css
I, [2015-04-25T17:58:46.493008 #16681]  INFO -- : Writing /home/mikes/rails/EcoDriver/public/assets/mystyle-70cce5ae11a71b412e69180a968d333d.css
I, [2015-04-25T17:58:46.497582 #16681]  INFO -- : Writing /home/mikes/rails/EcoDriver/public/assets/trips-86520fe950e8f54c4a42705ca501dccd.css
I, [2015-04-25T17:58:46.501622 #16681]  INFO -- : Writing /home/mikes/rails/EcoDriver/public/assets/users-86520fe950e8f54c4a42705ca501dccd.css
I, [2015-04-25T17:58:46.509965 #16681]  INFO -- : Writing /home/mikes/rails/EcoDriver/public/assets/utilities/_general-c557520ddf99f29f0865b15ec8f9e106.css
I, [2015-04-25T17:58:54.369379 #16681]  INFO -- : Writing /home/mikes/rails/EcoDriver/public/assets/welcome_page-934dc0e3ac9c29ad97d1cc13478e3ccd.css
I, [2015-04-25T17:58:54.386571 #16681]  INFO -- : Writing /home/mikes/rails/EcoDriver/public/assets/welcome_page/_form-b3be3aadee985aa02c0d3b25e39510d1.css
I, [2015-04-25T17:58:54.405405 #16681]  INFO -- : Writing /home/mikes/rails/EcoDriver/public/assets/welcome_page/_layout-9bf9b8f6208102ce8ae98c15753f8953.css
I, [2015-04-25T17:58:54.414697 #16681]  INFO -- : Writing /home/mikes/rails/EcoDriver/public/assets/ranking/index-f5717a5fb7e467d61618d90a75b893c6.js
I, [2015-04-25T17:58:54.421676 #16681]  INFO -- : Writing /home/mikes/rails/EcoDriver/public/assets/trips/index-23bb50797f5dbc636498a4e582aabb3d.js
I, [2015-04-25T17:58:54.502179 #16681]  INFO -- : Writing /home/mikes/rails/EcoDriver/public/assets/trips/mytrips-e143061c1600e83852903ca9a10a5b39.js
I, [2015-04-25T17:58:54.910150 #16681]  INFO -- : Writing /home/mikes/rails/EcoDriver/public/assets/ngmap-62f3230933e8e7b06478ba1aa35cdd87.js
I, [2015-04-25T17:58:55.405234 #16681]  INFO -- : Writing /home/mikes/rails/EcoDriver/public/assets/ngmap/ng-map.debug-2cd1a77a370dde9a38d8143f253d0f7a.js
I, [2015-04-25T17:58:55.782427 #16681]  INFO -- : Writing /home/mikes/rails/EcoDriver/public/assets/ngmap/ng-map-62f3230933e8e7b06478ba1aa35cdd87.js
I, [2015-04-25T17:58:55.916746 #16681]  INFO -- : Writing /home/mikes/rails/EcoDriver/public/assets/ngmap/config/jsdoc/template/static/styles/jsdoc-default-587683882678b05f6fa1959d2ba36ead.css
I, [2015-04-25T17:58:55.970232 #16681]  INFO -- : Writing /home/mikes/rails/EcoDriver/public/assets/ngmap/config/jsdoc/template/static/styles/prettify-jsdoc-bab63eaf363431eea30f9696ec25899c.css
I, [2015-04-25T17:58:56.095053 #16681]  INFO -- : Writing /home/mikes/rails/EcoDriver/public/assets/ngmap/config/jsdoc/template/static/styles/prettify-tomorrow-20b352776b83ef223a0569a4a579c162.css
rake aborted!
ExecJS::ProgramError: Unexpected token: operator (<) (line: 1, col: 0, pos: 0)

Error
    at new JS_Parse_Error (<eval>:2359:10623)
    at js_error (<eval>:2359:10842)
    at croak (<eval>:2359:19086)
    at token_error (<eval>:2359:19223)
    at unexpected (<eval>:2359:19311)
    at expr_atom (<eval>:2359:27526)
    at maybe_unary (<eval>:2359:30019)
    at expr_ops (<eval>:2359:30777)
    at maybe_conditional (<eval>:2359:30869)
    at maybe_assign (<eval>:2359:31312)
  (in /var/lib/gems/1.9.1/gems/rails-assets-ngmap-1.7.7/app/assets/templates/ngmap/testapp/aerial-rotate.html)new JS_Parse_Error ((execjs):2359:10623)
js_error ((execjs):2359:10842)
croak ((execjs):2359:19086)
token_error ((execjs):2359:19223)
unexpected ((execjs):2359:19311)
expr_atom ((execjs):2359:27526)
maybe_unary ((execjs):2359:30019)
expr_ops ((execjs):2359:30777)
maybe_conditional ((execjs):2359:30869)
maybe_assign ((execjs):2359:31312)
/var/lib/gems/1.9.1/gems/execjs-2.4.0/lib/execjs/ruby_racer_runtime.rb:47:in `rescue in block in call'
/var/lib/gems/1.9.1/gems/execjs-2.4.0/lib/execjs/ruby_racer_runtime.rb:44:in `block in call'
/var/lib/gems/1.9.1/gems/execjs-2.4.0/lib/execjs/ruby_racer_runtime.rb:75:in `block in lock'
/var/lib/gems/1.9.1/gems/execjs-2.4.0/lib/execjs/ruby_racer_runtime.rb:73:in `call'
/var/lib/gems/1.9.1/gems/execjs-2.4.0/lib/execjs/ruby_racer_runtime.rb:73:in `Locker'
/var/lib/gems/1.9.1/gems/execjs-2.4.0/lib/execjs/ruby_racer_runtime.rb:73:in `lock'
/var/lib/gems/1.9.1/gems/execjs-2.4.0/lib/execjs/ruby_racer_runtime.rb:43:in `call'
/var/lib/gems/1.9.1/gems/uglifier-2.7.1/lib/uglifier.rb:212:in `run_uglifyjs'
/var/lib/gems/1.9.1/gems/uglifier-2.7.1/lib/uglifier.rb:179:in `compile'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/compressing.rb:63:in `block (2 levels) in js_compressor='
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/processor.rb:29:in `call'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/processor.rb:29:in `evaluate'
/var/lib/gems/1.9.1/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/context.rb:197:in `block in evaluate'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/context.rb:194:in `each'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/context.rb:194:in `evaluate'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/bundled_asset.rb:25:in `initialize'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/base.rb:377:in `new'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/base.rb:377:in `build_asset'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/index.rb:94:in `block in build_asset'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/caching.rb:58:in `cache_asset'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/index.rb:93:in `build_asset'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/base.rb:287:in `find_asset'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/index.rb:61:in `find_asset'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:211:in `block in find_asset'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:257:in `benchmark'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:210:in `find_asset'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:119:in `block in compile'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:118:in `each'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:118:in `compile'
/var/lib/gems/1.9.1/gems/sprockets-rails-2.2.4/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/rake/sprocketstask.rb:146:in `with_logger'
/var/lib/gems/1.9.1/gems/sprockets-rails-2.2.4/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/var/lib/gems/1.9.1/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => assets:precompile
```

**Comment by allenhwkim** [comment]
Please do not add all for production. You only need ng map.min.js

**Comment by mikes01** [comment]
I removed /var/lib/gems/1.9.1/gems/rails-assets-ngmap-1.7.7/app/assets/templates/ngmap/testapp, after that everything works. Is it necessary to have testapp directory on master branch?

**Comment by allenhwkim** [comment]
master branch has every thing. If you use `bower install`, you won't have those files.
