### ISSUE TITLE
Unable to inject ngMap module. I follow the getting started guide line and still getting this error.

### ISSUE THREAD

**Issue by ravisangar** [allenhwkim/angularjs-google-maps#199]
I followed the DOC line by line as shown below:

$ bower install ngmap

Include ng-map.min.js as well as google maps.
<script src="http://maps.google.com/maps/api/js"></script>
<script src="http://rawgit.com/allenhwkim/angularjs-google-maps/master/build/scripts/ng-map.min.js"></script>

name angular app as ngMap, or add it as a dependency

var myApp = angular.module('myApp', ['ngMap']);

But keep getting this error.

Error: [$injector:unpr] Unknown provider: ngMapProvider <- ngMap
http://errors.angularjs.org/1.2.26/$injector/unpr?p0=ngMapProvider%20%3C-%20ngMap
    at VALIDITY_STATE_PROPERTY (http://localhost:8080/resources/bower_components/angular/angular.js:78:12)
    at http://localhost:8080/resources/bower_components/angular/angular.js:3802:19
    at Object.getService [as get] (http://localhost:8080/resources/bower_components/angular/angular.js:3930:39)
    at http://localhost:8080/resources/bower_components/angular/angular.js:3807:45
    at getService (http://localhost:8080/resources/bower_components/angular/angular.js:3930:39)
    at invoke (http://localhost:8080/resources/bower_components/angular/angular.js:3957:13)
    at Object.instantiate (http://localhost:8080/resources/bower_components/angular/angular.js:3977:23)
    at $get (http://localhost:8080/resources/bower_components/angular/angular.js:7281:28)
    at link (http://localhost:8080/resources/bower_components/angular-route/angular-route.js:907:26)
    at nodeLinkFn (http://localhost:8080/resources/bower_components/angular/angular.js:6711:13) <div ng-view="" class="container ng-scope">

**Comment by allenhwkim** [comment]
Please provide a plnkr, so that I can reproduce your problem on my end. Then, reopen this issue.
