### ISSUE TITLE
Lazy-load error when integrate with ionic 

### ISSUE THREAD

**Issue by SoaringTiger** [allenhwkim/angularjs-google-maps#247]
Hi, when I use map-lazy-load in ionic, there's an error. 
ionic version 1.0.1
ngmap version 1.9.0 

&lt;ion-content>
&lt;div map-lazy-load="//maps.google.com/maps/api/js">
            &lt;map center="41,-87" zoom="3"></map>
 &lt;/div>
&lt;/ion-content>

Error: [$injector:unpr] Unknown provider: nProvider <- n <- mapLazyLoadDirective
http://errors.angularjs.org/1.3.13/$injector/unpr?p0=nProvider%20%3C-%20n%20%3C-%20mapLazyLoadDirective
    at ionic.bundle.js:8890
    at ionic.bundle.js:12824
    at Object.getService [as get] (ionic.bundle.js:12971)
    at ionic.bundle.js:12829
    at getService (ionic.bundle.js:12971)
    at Object.invoke (ionic.bundle.js:13003)
    at ionic.bundle.js:15312
    at forEach (ionic.bundle.js:9150)
    at Object.<anonymous> (ionic.bundle.js:15310)
    at Object.invoke (ionic.bundle.js:13012)

ReferenceError: google is not defined
    at i (http://127.0.0.1:3000/lib/ngmap/build/scripts/ng-map.min.js:1:13696)
    at invokeLinkFn (http://127.0.0.1:3000/lib/ionic/js/ionic.bundle.js:17046:9)
    at nodeLinkFn (http://127.0.0.1:3000/lib/ionic/js/ionic.bundle.js:16556:11)
    at compositeLinkFn (http://127.0.0.1:3000/lib/ionic/js/ionic.bundle.js:15905:13)
    at compositeLinkFn (http://127.0.0.1:3000/lib/ionic/js/ionic.bundle.js:15908:13)
    at compositeLinkFn (http://127.0.0.1:3000/lib/ionic/js/ionic.bundle.js:15908:13)
    at nodeLinkFn (http://127.0.0.1:3000/lib/ionic/js/ionic.bundle.js:16551:24)
    at compositeLinkFn (http://127.0.0.1:3000/lib/ionic/js/ionic.bundle.js:15905:13)
    at nodeLinkFn (http://127.0.0.1:3000/lib/ionic/js/ionic.bundle.js:16551:24)
    at compositeLinkFn (http://127.0.0.1:3000/lib/ionic/js/ionic.bundle.js:15905:13) <map center="41,-87" zoom="3">

**Comment by allenhwkim** [comment]
updated 1.9.1. with this fix

**Comment by extravagangsta** [comment]
Thanks for the fix!

It also fixed ng-strict-di usage issue i had. Was getting the error below in Angular 1.4 and ngmap 1.9.0:
`Error: [$injector:strictdi] function(_$compile_, _$timeout_) is not using explicit annotation and cannot be invoked in strict mode`

After this fix everything works perfect.

**Comment by SoaringTiger** [comment]
Yeah! Great Works!
