### ISSUE TITLE
When trying to minify ng-map.js along with other scripts, the application fails. But it is ok with not minified version 

### ISSUE THREAD

**Issue by kuzman** [allenhwkim/angularjs-google-maps#394]
Error: [$injector:unpr] Unknown provider: _Attr2MapOptions_Provider <- _Attr2MapOptions_ <- __MapController
http://errors.angularjs.org/1.4.3/$injector/unpr?p0=_Attr2MapOptions_Provider%20%3C-Attr2MapOptions_%20%3C-%__MapController
    at file:///android_asset/www/scripts/vendor.js:1:2302
    at file:///android_asset/www/scripts/vendor.js:1:21642
    at Object.d [as get] (file:///android_asset/www/scripts/vendor.js:1:20812)
    at file:///android_asset/www/scripts/vendor.js:1:21739
    at d (file:///android_asset/www/scripts/vendor.js:1:20812)
    at Object.e [as invoke] (file:///android_asset/www/scripts/vendor.js:1:21149)
    at l.instance (file:///android_asset/www/scripts/vendor.js:2:11186)
    at q (file:///android_asset/www/scripts/vendor.js:2:842)
    at h (file:///android_asset/www/scripts/vendor.js:1:29318)
    at h (file:///android_asset/www/scripts/vendor.js:1:29341)

**Comment by allenhwkim** [comment]
I have tested it with gulp minifier, and it worked well. Can you give you your instruction how to minify it?

**Comment by kuzman** [comment]
we are using grunt uglify

**Comment by carlholloway** [comment]
I ran into a very similar, if not identical issue.
Turns out it wasn't the minification (I use gulp-uglify) at fault.
I needed to update to a newer version of gulp-ng-annotate, which fixed it.

Hope this helps.

**Comment by geisslercom** [comment]
sadly, i get the same error with grunt-ng-annonate ^0.2.3 .
Any tips?

**Comment by allenhwkim** [comment]
It seems upgrading grunt modules is the likely solution, closing this issue.
