### ISSUE TITLE
map lazy load info window won't work

### ISSUE THREAD

**Issue by jiagao** [allenhwkim/angularjs-google-maps#738]
The demo - https://ngmap.github.io/#/!map-lazy-load-params.html

info-window won't work. click on the pushpin, throw error -

```
Uncaught TypeError: Cannot read property 'showInfoWindow' of undefined
    at index (https://rawgit.com/allenhwkim/angularjs-google-maps/master/services/attr2-map-options.js:286:44)
    at Array.reduce (native)
    at _.ye.<anonymous> (https://rawgit.com/allenhwkim/angularjs-google-maps/master/services/attr2-map-options.js:287:39)
    at Object._.z.trigger (https://maps.google.com/maps/api/js?libraries=placeses,visualization,drawing,geometry,places:95:121)
    at VT.handleEvent (https://maps.google.com/maps-api-v3/api/js/27/5/marker.js:49:458)
    at _.tf.Jd (https://maps.google.com/maps-api-v3/api/js/27/5/common.js:189:417)
    at _.Nv._.k.re (https://maps.google.com/maps-api-v3/api/js/27/5/common.js:239:205)
    at _.Nv._.k.Xi (https://maps.google.com/maps-api-v3/api/js/27/5/common.js:238:246)
    at Object._.z.trigger (https://maps.google.com/maps/api/js?libraries=placeses,visualization,drawing,geometry,places:95:121)
    at Pt.<anonymous> (https://maps.google.com/maps-api-v3/api/js/27/5/common.js:138:342)
```

**Comment by jiagao** [comment]
@allenhwkim would you mind to share your feedback?

**Comment by allenhwkim** [comment]
The example has a bug in it. Please use this.

http://plnkr.co/edit/nBO6txbEVeDt4AhWfHZ8?p=preview

**Comment by jiagao** [comment]
It works. thank you..
