### ISSUE TITLE
Using md-button in custom-component throws ngTransclude:orphan error

### ISSUE THREAD

**Issue by stillgbx** [allenhwkim/angularjs-google-maps#754]
Using some `angular-material` directives (like `md-button`, `md-checkbox` ...) in `custom-component` throws `ngTransclude:orphan` error.

**Steps to reproduce and a minimal demo(Plunker Example)**
1. Add `ng-map`
2. Add a `custom-component` containing a `md-button`

See http://plnkr.co/edit/WvcpUcBpMDYMbX9fnU2j?p=preview

**Current behavior**

 - Throws an error
 ```
Error: [ngTransclude:orphan] http://errors.angularjs.org/1.6.1/ngTransclude/orphan?p0=%3Cbuttonlass%3D%22md-button%20md-ink-ripple%20ng-scope%22%20type%3D%22button%22%20ng-transclude%3D%22%22%3E
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular.min.js:6:425
    at Object.<anonymous> (http://ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular.min.js:315:303)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular.min.js:16:71
    at ta (http://ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular.min.js:84:35)
    at n (http://ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular.min.js:69:226)
    at g (http://ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular.min.js:60:496)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular.min.js:60:119
    at Object.linkFunc [as link] (https://rawgit.com/allenhwkim/angularjs-google-maps/master/build/scripts/ng-map.js:428:47)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular.min.js:16:71
    at ta (http://ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular.min.js:84:35)
```

**Expected/desired behavior**

  - No error

**Other information**

  - Using transclusion with `$transclude()` rather than `$compile()` innerHTML of the `custom-component` seems to fix the issue.
  - I'll link a PR.

**Comment by edgarMejia** [comment]
Can you give me an example of how to solve the error?
