### ISSUE TITLE
Marker tags not inside map throw error

### ISSUE THREAD

**Issue by pmannle** [allenhwkim/angularjs-google-maps#871]
Hi all, great libarary, but I've run into an issue: When I have an additional SVG marker on the same page as the map, I get the following error (see below).

I've created to plunkr to demonstrate - you can see the error in the console logs:

http://plnkr.co/edit/f909ajVIBBrkQohgq8ME?p=preview

Is there any way to add other svg graphics to the same html page without ng-maps throwing the following error?:

angular.js:11655 TypeError: Cannot read property 'addObject' of null
    at linkFunc (https://rawgit.com/allenhwkim/angularjs-google-maps/master/build/scripts/ng-map.js:1869:19)
    at invokeLinkFn (https://code.angularjs.org/1.3.15/angular.js:8258:9)
    at nodeLinkFn (https://code.angularjs.org/1.3.15/angular.js:7768:11)
    at compositeLinkFn (https://code.angularjs.org/1.3.15/angular.js:7117:13)
    at compositeLinkFn (https://code.angularjs.org/1.3.15/angular.js:7120:13)
    at compositeLinkFn (https://code.angularjs.org/1.3.15/angular.js:7120:13)
    at compositeLinkFn (https://code.angularjs.org/1.3.15/angular.js:7120:13)
    at publicLinkFn (https://code.angularjs.org/1.3.15/angular.js:6996:30)
    at https://code.angularjs.org/1.3.15/angular.js:1457:27
    at Scope.$eval (https://code.angularjs.org/1.3.15/angular.js:14466:28) <marker id="arrowMarker2" viewBox="0 0 36 21" refX="21" refY="10" markerUnits="strokeWidth" orient="auto" markerWidth="16" markerHeight="12">

**Comment by allenhwkim** [comment]
https://docs.angularjs.org/api/ng/directive/ngNonBindable
Please use this directive if it is SVG tag.
